[package]
name = "openjpeg2000"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]
build = "build.rs"

[dependencies]
image = "0.17.0"

[build-dependencies]
bindgen = "0.31.3"
cmake = "0.1.27"
gcc = "0.3.54"
