[package]
name = "openjp2-sys"
version = "0.1.0"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]
links = "openjp2"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.31.3"
cmake = "0.1.27"
gcc = "0.3.54"
